# Generated by Django 5.2.3 on 2025-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
