# Generated by Django 5.2.3 on 2025-07-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_entrepreneur',
            field=models.BooleanField(default=False, verbose_name='Tadbirkormi?'),
        ),
    ]
