# Generated by Django 5.2.3 on 2025-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramprofile_is_entrepreneur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='near_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Near loyihasi User IDsi'),
        ),
    ]
