# Generated by Django 5.2.3 on 2025-07-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_telegramprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramprofile',
            name='is_entrepreneur',
        ),
    ]
